### ISSUE TITLE
Amazing!

### ISSUE THREAD

**Issue by Axel-Naumann** [SdtElectronics/cline#4]
Hi @SdtElectronics - amazing work! @vgvassilev maybe that's a good topic for your compiler-as-a-service series? I'd be curious to hear how you did it, e.g. the security isolation is pretty neat. And we (https://root.cern) would *love* to have a blog post from you! But better do that only if you can handle some hundreds of concurrent users ;-) Let me know, please!

And yeah, this isn't a bug report, sorry :-)

**Comment by SdtElectronics** [comment]
I planned to write a post on the Root Forum as well, but I feel a bit tired yesterday after posting on Reddit. I haven't done any performance testing yet, thus I'm not sure about how well it scales. I did limit the memory consumption per user with the load like one hundred active sessions in mind, though. Probably the best way to see whether it can handle is to try it out.

For security measurements, it combined multiple technologies together, including seccomp, AppArmor and docker. I'd like to talk more about it, but to be honest I'm not quite confident about how secure it is for now. In fact, one reason I decided to announce it early is I want to see if anyone is able to break the confined environment :P

**Comment by SdtElectronics** [comment]
@Axel-Naumann I just posted [an introduction to this project on my blog](https://sdtelectronics.github.io/projects/2023-2-15-Cline-The-Online-C++-Interpreter.html). I'd be happy to have this reposted on your site! Check the original markdown file at [https://github.com/SdtElectronics/sdtelectronics.github.io/blob/master/collections/_projects/2023-2-15-Cline-The-Online-C%2B%2B-Interpreter.md](https://github.com/SdtElectronics/sdtelectronics.github.io/blob/master/collections/_projects/2023-2-15-Cline-The-Online-C%2B%2B-Interpreter.md)
