### ISSUE TITLE
https://cppcli.net: Execution aborted. Possible security policy violation

### ISSUE THREAD

**Issue by edfink234** [SdtElectronics/cline#6]
Threads don't seem to work with https://cppcli.net. The following MWE:

```C++
#include <iostream>
#include <thread>
auto f = [](){std::cout << "hello\n";};
std::thread t{f};
```

produces the following output (after taking some time to load):

`
Execution aborted. Possible security policy violation
`

Is there a workaround for this?

Btw nice work, it's really cool!

**Comment by SdtElectronics** [comment]
Creation of threads and processes were intentionally disabled due to difficulties on resource management, e.g. fork bomb, `while(1);` on multiple threads, etc. If I or someone find a way to manage this later, it can be enabled at that time.
